/*
 * This file is generated by jOOQ.
 */
package com.org.irctc;


import com.org.irctc.tables.Booking;
import com.org.irctc.tables.Seat;
import com.org.irctc.tables.Train;
import com.org.irctc.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Irctc extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>irctc</code>
     */
    public static final Irctc IRCTC = new Irctc();

    /**
     * The table <code>irctc.booking</code>.
     */
    public final Booking BOOKING = Booking.BOOKING;

    /**
     * The table <code>irctc.seat</code>.
     */
    public final Seat SEAT = Seat.SEAT;

    /**
     * The table <code>irctc.train</code>.
     */
    public final Train TRAIN = Train.TRAIN;

    /**
     * The table <code>irctc.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Irctc() {
        super("irctc", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Booking.BOOKING,
            Seat.SEAT,
            Train.TRAIN,
            User.USER
        );
    }
}
