/*
 * This file is generated by jOOQ.
 */
package com.org.irctc;


import com.org.irctc.tables.Booking;
import com.org.irctc.tables.Seat;
import com.org.irctc.tables.Train;
import com.org.irctc.tables.User;


/**
 * Convenience access to all tables in irctc.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>irctc.booking</code>.
     */
    public static final Booking BOOKING = Booking.BOOKING;

    /**
     * The table <code>irctc.seat</code>.
     */
    public static final Seat SEAT = Seat.SEAT;

    /**
     * The table <code>irctc.train</code>.
     */
    public static final Train TRAIN = Train.TRAIN;

    /**
     * The table <code>irctc.user</code>.
     */
    public static final User USER = User.USER;
}
