/*
 * This file is generated by jOOQ.
 */
package com.org.irctc.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Train implements Serializable {

    private static final long serialVersionUID = 1L;

    private String trainId;
    private String trainNumber;
    private String trainName;
    private String source;
    private String destination;
    private String createdBy;
    private LocalDateTime createdDate;
    private String modifiedBy;
    private LocalDateTime modifiedDate;
    private String status;

    public Train() {}

    public Train(Train value) {
        this.trainId = value.trainId;
        this.trainNumber = value.trainNumber;
        this.trainName = value.trainName;
        this.source = value.source;
        this.destination = value.destination;
        this.createdBy = value.createdBy;
        this.createdDate = value.createdDate;
        this.modifiedBy = value.modifiedBy;
        this.modifiedDate = value.modifiedDate;
        this.status = value.status;
    }

    public Train(
        String trainId,
        String trainNumber,
        String trainName,
        String source,
        String destination,
        String createdBy,
        LocalDateTime createdDate,
        String modifiedBy,
        LocalDateTime modifiedDate,
        String status
    ) {
        this.trainId = trainId;
        this.trainNumber = trainNumber;
        this.trainName = trainName;
        this.source = source;
        this.destination = destination;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.status = status;
    }

    /**
     * Getter for <code>irctc.train.train_id</code>.
     */
    public String getTrainId() {
        return this.trainId;
    }

    /**
     * Setter for <code>irctc.train.train_id</code>.
     */
    public void setTrainId(String trainId) {
        this.trainId = trainId;
    }

    /**
     * Getter for <code>irctc.train.train_number</code>.
     */
    public String getTrainNumber() {
        return this.trainNumber;
    }

    /**
     * Setter for <code>irctc.train.train_number</code>.
     */
    public void setTrainNumber(String trainNumber) {
        this.trainNumber = trainNumber;
    }

    /**
     * Getter for <code>irctc.train.train_name</code>.
     */
    public String getTrainName() {
        return this.trainName;
    }

    /**
     * Setter for <code>irctc.train.train_name</code>.
     */
    public void setTrainName(String trainName) {
        this.trainName = trainName;
    }

    /**
     * Getter for <code>irctc.train.source</code>.
     */
    public String getSource() {
        return this.source;
    }

    /**
     * Setter for <code>irctc.train.source</code>.
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * Getter for <code>irctc.train.destination</code>.
     */
    public String getDestination() {
        return this.destination;
    }

    /**
     * Setter for <code>irctc.train.destination</code>.
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * Getter for <code>irctc.train.created_by</code>.
     */
    public String getCreatedBy() {
        return this.createdBy;
    }

    /**
     * Setter for <code>irctc.train.created_by</code>.
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * Getter for <code>irctc.train.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return this.createdDate;
    }

    /**
     * Setter for <code>irctc.train.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * Getter for <code>irctc.train.modified_by</code>.
     */
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    /**
     * Setter for <code>irctc.train.modified_by</code>.
     */
    public void setModifiedBy(String modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    /**
     * Getter for <code>irctc.train.modified_date</code>.
     */
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }

    /**
     * Setter for <code>irctc.train.modified_date</code>.
     */
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * Getter for <code>irctc.train.status</code>.
     */
    public String getStatus() {
        return this.status;
    }

    /**
     * Setter for <code>irctc.train.status</code>.
     */
    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Train other = (Train) obj;
        if (this.trainId == null) {
            if (other.trainId != null)
                return false;
        }
        else if (!this.trainId.equals(other.trainId))
            return false;
        if (this.trainNumber == null) {
            if (other.trainNumber != null)
                return false;
        }
        else if (!this.trainNumber.equals(other.trainNumber))
            return false;
        if (this.trainName == null) {
            if (other.trainName != null)
                return false;
        }
        else if (!this.trainName.equals(other.trainName))
            return false;
        if (this.source == null) {
            if (other.source != null)
                return false;
        }
        else if (!this.source.equals(other.source))
            return false;
        if (this.destination == null) {
            if (other.destination != null)
                return false;
        }
        else if (!this.destination.equals(other.destination))
            return false;
        if (this.createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!this.createdBy.equals(other.createdBy))
            return false;
        if (this.createdDate == null) {
            if (other.createdDate != null)
                return false;
        }
        else if (!this.createdDate.equals(other.createdDate))
            return false;
        if (this.modifiedBy == null) {
            if (other.modifiedBy != null)
                return false;
        }
        else if (!this.modifiedBy.equals(other.modifiedBy))
            return false;
        if (this.modifiedDate == null) {
            if (other.modifiedDate != null)
                return false;
        }
        else if (!this.modifiedDate.equals(other.modifiedDate))
            return false;
        if (this.status == null) {
            if (other.status != null)
                return false;
        }
        else if (!this.status.equals(other.status))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.trainId == null) ? 0 : this.trainId.hashCode());
        result = prime * result + ((this.trainNumber == null) ? 0 : this.trainNumber.hashCode());
        result = prime * result + ((this.trainName == null) ? 0 : this.trainName.hashCode());
        result = prime * result + ((this.source == null) ? 0 : this.source.hashCode());
        result = prime * result + ((this.destination == null) ? 0 : this.destination.hashCode());
        result = prime * result + ((this.createdBy == null) ? 0 : this.createdBy.hashCode());
        result = prime * result + ((this.createdDate == null) ? 0 : this.createdDate.hashCode());
        result = prime * result + ((this.modifiedBy == null) ? 0 : this.modifiedBy.hashCode());
        result = prime * result + ((this.modifiedDate == null) ? 0 : this.modifiedDate.hashCode());
        result = prime * result + ((this.status == null) ? 0 : this.status.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Train (");

        sb.append(trainId);
        sb.append(", ").append(trainNumber);
        sb.append(", ").append(trainName);
        sb.append(", ").append(source);
        sb.append(", ").append(destination);
        sb.append(", ").append(createdBy);
        sb.append(", ").append(createdDate);
        sb.append(", ").append(modifiedBy);
        sb.append(", ").append(modifiedDate);
        sb.append(", ").append(status);

        sb.append(")");
        return sb.toString();
    }
}
